site_name: Documentation des APIs du repo lmelp
nav:
  - Accueil: index.md
  - Modules:
      - Module config: config.md
      - Module llm: llm.md
      - Module whisper: whisper.md
      - Module web: web.md
      - Module rss: rss.md
      - Module mongo: mongo.md
      - Module mongo_episode: mongo_episode.md
      - Module mongo_auteur: mongo_auteur.md
      - Module mongo_livre: mongo_livre.md
  - Other kind of docs:
      - manage doc: readme_doc.md
      - write markdown: readme_markdown.md
      - some vs_code hints: readme_vscode_hints.md
      - about Google services: readme_google.md
      - data model: readme_data_model.md
      - github: readme_github.md
      - uv devcontainer venv: readme_uv_devcontainer.md
      - import strategy: readme_import_strategy.md
      - unit tests guide: readme_unit_test.md
theme:
  name: material

# Configuration de mkdocstrings pour extraire la documentation de vos .py
markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [nbs]