site_name: Documentation des APIs du repo lmelp
nav:
  - Accueil: index.md
  - Modules:
      - Module llm: llm.md
      - Module whisper: whisper.md
      - Module web: web.md
      - Module rss: rss.md
      - Module mongo: mongo.md
      - Module mongo_episode: mongo_episode.md
      - Module mongo_auteur: mongo_auteur.md
  - Other kind of docs:
      - To manage doc: readme_doc.md
      - To write markdown: readme_markdown.md
      - some vs_code hints: readme_vscode_hints.md
      - about Google services: readme_google.md
theme:
  name: material

# Configuration de mkdocstrings pour extraire la documentation de vos .py
markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [nbs]