# AUTOGENERATED! DO NOT EDIT! File to edit: py config.ipynb.

# %% auto 0
__all__ = ["load_env", "get_RSS_URL"]

# %% py config.ipynb 2
from dotenv import load_dotenv, find_dotenv
import os


def load_env() -> None:
    """
    Charge les variables d'environnement à partir d'un fichier .env.
    """
    _ = load_dotenv(find_dotenv())


def get_RSS_URL() -> str:
    """
    Récupère l'URL du flux RSS à partir des variables d'environnement.

    Returns:
        str: L'URL du flux RSS. Si la variable d'environnement `RSS_LMELP_URL` n'est pas définie,
        retourne une URL par défaut.
    """
    load_env()
    RSS_LMELP_URL = os.getenv("RSS_LMELP_URL")
    if RSS_LMELP_URL is None:
        RSS_LMELP_URL = "https://radiofrance-podcast.net/podcast09/rss_14007.xml"
    return RSS_LMELP_URL
