# AUTOGENERATED! DO NOT EDIT! File to edit: 07 connection mongo.ipynb.

# %% auto 0
__all__ = ["get_collection"]

# %% 07 connection mongo.ipynb 2
import pymongo


def get_collection(
    target_db="localhost", client_name="masque_et_la_plume", collection_name="episodes"
):
    """
    target_db can be 'localhost' or 'nas923'
    """
    client = pymongo.MongoClient(f"mongodb://{target_db}:27017/")
    db = client[client_name]
    collection = db[collection_name]
    return collection
