# AUTOGENERATED! DO NOT EDIT! File to edit: helper.ipynb.

# %% auto 0
__all__ = ["load_env", "get_gemini_api_key", "get_gemini_llm"]

# %% helper.ipynb 1
from dotenv import load_dotenv, find_dotenv
import os


def load_env():
    _ = load_dotenv(find_dotenv())


def get_gemini_api_key():
    load_env()
    gemini_api_key = os.getenv("GEMINI_API_KEY")
    return gemini_api_key


# %% helper.ipynb 3
import google.generativeai as genai


def get_gemini_llm(model="gemini-1.5-flash"):
    genai.configure(api_key=get_gemini_api_key())
    llm = genai.GenerativeModel(model)
    return llm
