# AUTOGENERATED! DO NOT EDIT! File to edit: py mongo helper avis_critiques.ipynb.

# %% auto 0
__all__ = ["AvisCritique"]

# %% py mongo helper avis_critiques.ipynb 3
__all__ = ["T", "AvisCritique", "get_collection"]

# %% py mongo helper avis_critiques.ipynb 4
from mongo import BaseEntity


class AvisCritique(BaseEntity):
    collection: str = "avis_critiques"

    def __init__(
        self,
        episode_id,
        entity_type,
        entity_name,
        summary_text=None,
        created_at=None,
        updated_at=None,
    ):
        super().__init__(episode_id, self.collection)
        self.episode_id = episode_id
        self.entity_type = entity_type
        self.entity_name = entity_name
        self.summary_text = summary_text
        self.created_at = created_at or datetime.datetime.now()
        self.updated_at = updated_at or datetime.datetime.now()

    @property
    def nom(self):
        return f"{self.entity_type}_{self.entity_name}_{self.episode_id}"

    @classmethod
    def from_oid(cls, oid):
        DB_HOST, DB_NAME, _ = get_DB_VARS()
        coll = get_collection(DB_HOST, DB_NAME, cls.collection)
        doc = coll.find_one({"_id": oid})
        if not doc:
            return None
        return cls(
            episode_id=doc.get("episode_id"),
            entity_type=doc.get("entity_type"),
            entity_name=doc.get("entity_name"),
            summary_text=doc.get("summary_text"),
            created_at=doc.get("created_at"),
            updated_at=doc.get("updated_at"),
        )

    @classmethod
    def find_by_episode_and_entity(cls, episode_id, entity_type, entity_name):
        DB_HOST, DB_NAME, _ = get_DB_VARS()
        coll = get_collection(DB_HOST, DB_NAME, cls.collection)
        docs = coll.find(
            {
                "episode_id": episode_id,
                "entity_type": entity_type,
                "entity_name": entity_name,
            }
        )
        return [
            cls(
                episode_id=doc.get("episode_id"),
                entity_type=doc.get("entity_type"),
                entity_name=doc.get("entity_name"),
                summary_text=doc.get("summary_text"),
                created_at=doc.get("created_at"),
                updated_at=doc.get("updated_at"),
            )
            for doc in docs
        ]

    @classmethod
    def find_by_episode_id(cls, episode_id):
        DB_HOST, DB_NAME, _ = get_DB_VARS()
        coll = get_collection(DB_HOST, DB_NAME, cls.collection)
        docs = coll.find({"episode_id": episode_id})
        return [
            cls(
                episode_id=doc.get("episode_id"),
                entity_type=doc.get("entity_type"),
                entity_name=doc.get("entity_name"),
                summary_text=doc.get("summary_text"),
                created_at=doc.get("created_at"),
                updated_at=doc.get("updated_at"),
            )
            for doc in docs
        ]

    def __str__(self):
        if self.summary_text:
            return f"AvisCritique({self.nom}): {self.summary_text}"
        return f"AvisCritique({self.nom})"
