# AUTOGENERATED! DO NOT EDIT! File to edit: py mongo helper auteurs.ipynb.

# %% auto 0
__all__ = ["Auteur"]

# %% py mongo helper auteurs.ipynb 2
from mongo import BaseEntity


class Auteur(BaseEntity):
    collection = "auteurs"

    def __init__(self, nom: str):
        """
        Auteur is a class that represents an author in the database auteurs.
        :param nom: The name of the author.
        """
        super().__init__(nom, self.collection)
